# This is a basic workflow to help you get started with Actions

name: Mega login

# Controls when the workflow will run
on:
  schedule:
   - cron:  '00 00,06,12,18 * * *' 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Lets do it
        run: |
          git clone https://${{secrets.MT}}@github.com/darkarmyworld/work
          pip3 install mega.py
          cd work;python3 login.py
